# Generated by Django 4.2 on 2023-04-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age')),
                ('gender', models.CharField(blank=True, max_length=100, null=True, verbose_name='gender')),
                ('phoneNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='phoneNo')),
                ('addressDetails', models.JSONField()),
                ('hno', models.CharField(blank=True, max_length=100, null=True, verbose_name='hno')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='street')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='state')),
                ('workExeperience', models.JSONField()),
                ('companyName', models.CharField(blank=True, max_length=100, null=True, verbose_name='companyName')),
                ('fromDate', models.CharField(blank=True, max_length=100, null=True, verbose_name='fromdate')),
                ('toDate', models.CharField(blank=True, max_length=100, null=True, verbose_name='todate')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('qualificiations', models.JSONField()),
                ('qualificationName', models.CharField(blank=True, max_length=100, null=True, verbose_name='qualificationName')),
                ('percentage', models.IntegerField(null=True)),
                ('projects', models.JSONField()),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='photo')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
            },
        ),
    ]
