# Generated by Django 4.2 on 2023-04-06 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hno', models.CharField(blank=True, max_length=100, null=True, verbose_name='hno')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='street')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='state')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificationName', models.CharField(blank=True, max_length=100, null=True, verbose_name='qualificationName')),
                ('percentage', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=100, null=True, verbose_name='companyName')),
                ('fromDate', models.CharField(blank=True, max_length=100, null=True, verbose_name='fromdate')),
                ('toDate', models.CharField(blank=True, max_length=100, null=True, verbose_name='todate')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
            ],
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='fromDate',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='hno',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='qualificationName',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='street',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='title',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='toDate',
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='addressDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeedata.addressdetails'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeedata.projects'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='qualificiations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeedata.qualification'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='workExeperience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeedata.workexperience'),
        ),
    ]
