# Generated by Django 4.2 on 2023-04-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeedata', '0002_addressdetails_projects_qualification_workexperience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='addressDetails',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeedata.addressdetails'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='projects',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeedata.projects'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='qualificiations',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeedata.qualification'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='workExeperience',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeedata.workexperience'),
        ),
    ]
