# Generated by Django 4.2 on 2023-04-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedata', '0003_alter_employeedata_addressdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='fromDate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='fromdate'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='toDate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='todate'),
        ),
    ]
