# Generated by Django 4.2 on 2023-04-07 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeedata', '0004_qualification_fromdate_qualification_todate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='addressDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeedata.addressdetails'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeedata.projects'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='qualificiations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeedata.qualification'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='workExeperience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeedata.workexperience'),
        ),
    ]
