# Generated by Django 4.2 on 2023-04-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedata', '0005_alter_employeedata_addressdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='addressDetails',
            field=models.TextField(blank=True, null=True, verbose_name='addressDetails'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='projects',
            field=models.TextField(blank=True, null=True, verbose_name='projects'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='qualificiations',
            field=models.TextField(blank=True, null=True, verbose_name='qualificiations'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='workExeperience',
            field=models.TextField(blank=True, null=True, verbose_name='workExeperience'),
        ),
    ]
