# Generated by Django 4.2 on 2023-04-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedata', '0006_alter_employeedata_addressdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='regid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='regid'),
        ),
    ]
